---
title: Arthurs Point
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Alternative folk band from Wookey Hole.'
author: Test
baseurl:
url:
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
